// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeTL1WyMvwHPQnndU4NW38XML6Mm7xPq0',
    appId: '1:727134670816:web:0550cb3c982e6651cba585',
    messagingSenderId: '727134670816',
    projectId: 'taskflow-61b9d',
    authDomain: 'taskflow-61b9d.firebaseapp.com',
    storageBucket: 'taskflow-61b9d.firebasestorage.app',
    measurementId: 'G-HV0LFYQY2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARHwqzjg416aJpxlRx62J6mFKPg9Em_FY',
    appId: '1:727134670816:android:87aca8fba0a11903cba585',
    messagingSenderId: '727134670816',
    projectId: 'taskflow-61b9d',
    storageBucket: 'taskflow-61b9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsJSy7f3Pmot8SVICpVVMGhDvHbNL2F24',
    appId: '1:727134670816:ios:5b354f2a6ba7ca08cba585',
    messagingSenderId: '727134670816',
    projectId: 'taskflow-61b9d',
    storageBucket: 'taskflow-61b9d.firebasestorage.app',
    iosBundleId: 'br.com.taskflow.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsJSy7f3Pmot8SVICpVVMGhDvHbNL2F24',
    appId: '1:727134670816:ios:75ef22c6d88ee0b5cba585',
    messagingSenderId: '727134670816',
    projectId: 'taskflow-61b9d',
    storageBucket: 'taskflow-61b9d.firebasestorage.app',
    iosBundleId: 'com.example.taskflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeTL1WyMvwHPQnndU4NW38XML6Mm7xPq0',
    appId: '1:727134670816:web:cb88d87bc1f2a90acba585',
    messagingSenderId: '727134670816',
    projectId: 'taskflow-61b9d',
    authDomain: 'taskflow-61b9d.firebaseapp.com',
    storageBucket: 'taskflow-61b9d.firebasestorage.app',
    measurementId: 'G-71QY6M25HR',
  );

}